name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v1 
      with:
        java-version: '11'
    - name: Build package      
      run: mvn --batch-mode package --file pom.xml  
    - name: Upload build artifacts       
      uses: actions/upload-artifact@v2      
      with:        
        name: simplewebservice.jar        
        path: target/simplewebservice.jar
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nicklissens/simplewebservice2:$(date +%s)
    - name: Push the Docker image
      run: docker push nicklissens/simplewebservice2:latest nicklissens/simplewebservice2
