name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v1 
      with:
        java-version: '11'
    - name: Build package      
      run: mvn --batch-mode package --file pom.xml  
    - name: Upload build artifacts       
      uses: actions/upload-artifact@v2      
      with:        
        name: simplewebservice.jar        
        path: target/simplewebservice.jar
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_NAME }}
        password: ${{secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      uses: docker/setup-buildx-action@v2
    - name: Build & push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
