name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v1 
      with:
        java-version: '11'
    - name: Build package      
      run: | 
        mvn clean package
        mkdir target && cp target/*.jar target
    - name: Upload build artifacts       
      uses: actions/upload-artifact@v2      
      with:
        name: simplewebservice.jar 
        path: target
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_NAME }}
        password: ${{secrets.DOCKER_PASSWORD }}
    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{secrets.DOCKER_NAME}}/simplewebservice2
    - name: Build the Docker image
      uses: docker/setup-buildx-action@v2
    - name: Build & push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
