name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: mkdir target
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build package      
      run: | 
        mvn clean package
    - name: Upload build artifacts       
      uses: actions/upload-artifact@v3     
      with:
        name: simplewebservice.jar
        path: target/
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_NAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Get tag
      id: tag_name
      run: SNAPSHOT=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) && echo "::set-output name=version::$SNAPSHOT"
    - name: Build image
      run: docker build -t simplewebservice2 .
    - name: Tag image
      run: docker tag simplewebservice2 ${{secrets.DOCKER_NAME}}/simplewebservice2:${{steps.tag_name.outputs.version}}
    - name: Push Docker images
      run: docker push ${{secrets.DOCKER_NAME}}/simplewebservice2:${{steps.tag_name.outputs.version}}

